DataConnectBundle\Entity\Tblcsvbrick:
    type: entity
    table: tblCSVBrick
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        delimiter:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        filePath:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: file_path
    lifecycleCallbacks: {  }
